# Generated by Django 4.2.23 on 2025-09-21 09:35

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateTemperature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('open_meteo_value', models.FloatField(blank=True, null=True)),
                ('nasa_value', models.FloatField(blank=True, null=True)),
                ('ncei_value', models.FloatField(blank=True, null=True)),
                ('mean_value', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, help_text='Store same as mean_value (but allows flexibility if different calc later)', null=True)),
                ('measurement_unit', models.CharField(max_length=20)),
                ('unit_standardized', models.CharField(default='Celsius', max_length=20)),
                ('source', models.CharField(default='aggregated', max_length=50)),
                ('aggregation_method', models.CharField(default='mean', max_length=50)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Set once')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Updated on Save')),
            ],
            options={
                'db_table': 'climate_temperature',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['latitude', 'longitude', 'year'], name='climate_tem_latitud_335c96_idx')],
            },
        ),
    ]
