# Generated by Django 4.2.23 on 2025-09-21 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0002_climatetemperature_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climatetemperature',
            name='month',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
