# Generated by Django 4.2.23 on 2025-10-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0004_climate_delete_climatetemperature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climate',
            old_name='country',
            new_name='country_code',
        ),
        migrations.AddField(
            model_name='climate',
            name='country_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
